#include<string.h>
#include<stdio.h>
#include<stdlib.h>
#include<unistd.h> //linux specific library for fork related calls
#include<time.h>
#include<sys/wait.h>
#include<errno.h>

int main(int argc, char *argv)
{
    int fd1[2];
    int fd2[2];
    //fd[0] for read
    //fd[1] for write
    pipe(fd1);
    pipe(fd2);

    int id = fork();
    if(id == -1)
    {
        printf("fork error\n");
        return 1;
    }
    else if(id > 0) // parent
    {
        char str1[108] = "Operating systems course taught by ";
        printf("String 1 generated by parent is #%s#\n", str1);
        char rstr[108];
        int s1len = strlen(str1);
        int rslen;

        close(fd1[1]);
        read(fd1[0], &rslen, sizeof(int));
        read(fd1[0], rstr, rslen*sizeof(char));
        close(fd1[0]);
    
        strcat(str1, rstr);
        printf("Final string from child = %s\n", str1);
        s1len = strlen(str1);

        close(fd2[0]);
        write(fd2[1], &s1len, sizeof(int));
        write(fd2[1], str1, s1len*sizeof(char));
        close(fd2[1]);

        wait(NULL);

    }
    else // child
    {
        char str2[108] = "Sivaselvan sir";
        printf("String 2 generated by child is #%s#\n", str2);
        int s2len = strlen(str2);
        int slen;

        close(fd1[0]);
        write(fd1[1], &s2len, sizeof(int));
        write(fd1[1], str2, s2len*sizeof(char));
        close(fd1[1]);

        close(fd2[1]);
        read(fd2[0], &slen, sizeof(int));
        read(fd2[0], str2, slen*sizeof(char));
        close(fd2[0]);

        printf("Final string from parent = %s\n", str2);
    }

    return 0;
}