#include<string.h>
#include<stdio.h>
#include<stdlib.h>
#include<unistd.h> //linux specific library for fork related calls
#include<time.h>
#include<sys/wait.h>
#include<errno.h>

int main(int argc, char *argv)
{
    int fd1[2];
    //fd[0] for read
    //fd[1] for write
    pipe(fd1);

    int id = fork();
    if(id == -1)
    {
        printf("fork error\n");
        return 1;
    }
    else if(id > 0) // parent
    {
        char str[108] = "OperatingSystemCourse";
        printf("String generated by parent = %s\n", str);
        int slen = strlen(str);
        int start, end;
        printf("Enter the start index of substring : ");
        scanf("%d", &start);
        printf("Enter the end index of substring : ");
        scanf("%d", &end);

        close(fd1[0]);
        write(fd1[1], &slen, sizeof(int));
        write(fd1[1], str, strlen(str)*sizeof(char));
        write(fd1[1], &start, sizeof(int));
        write(fd1[1], &end, sizeof(int));
        close(fd1[1]);

        wait(NULL);

    }
    else // child
    {
        char rstr[108];
        int rslen;
        int start, end;
        char substr[108];
        
        close(fd1[1]);
        read(fd1[0], &rslen, sizeof(int));
        read(fd1[0], rstr, rslen*sizeof(char));
        read(fd1[0], &start, sizeof(int));
        read(fd1[0], &end, sizeof(int));
        close(fd1[0]);

        for(int i = start; i <= end; i++)
            substr[i-start] = rstr[i];

        printf("Substring generated at child = %s\n", substr);
    }

    return 0;
}